### ISSUE TITLE
Fix checking of date and time clash

### ISSUE THREAD

**Issue by jltha** [AY2122S2-CS2113T-T09-1/tp#95]
To add junit tests and find out why the bug occured, i.e. some test cases with time clash were being added in the task when editing of a task occurs.

Test case (Only instructions available:)
add testing3 /do 1/4/2022 /start 11:00 /end 12:00 /repeat WEEKLY
edit 8 /do 18/5/2022 /start 10:00 /end 12:00 /repeat
edit 9 /do 18/05/2022 /start 11:00 /end 12:00 /by 30/5/2022

**Comment by thedarie** [comment]
the first two lines can be removed, a more concise test case is:

add testing3 /do 1/4/2022 /start 11:00 /end 12:00 /repeat WEEKLY
edit 8 /do 18/5/2022 /start 10:00 /end 12:00 /repeat
edit 9 /do 18/05/2022 /start 11:00 /end 12:00 /by 30/5/2022

notice if you try to edit 8 into conflict with 7, it does detect a clash. weird bug
